--==========================================================================================================================
-- MEXICO_NAMES
--==========================================================================================================================
INSERT OR REPLACE INTO LocalizedText
		(Tag, Language,	Text)
VALUES
---------------------------------------------------------------------------------------------------------------------------
-- Citizen Names
----------------------------------------------------------------------------------------------------------------------------
		------------------------------------------------------- Ancient Male ------------
		("LOC_CITIZEN_LEU_MEXICO_MALE_1",			"en_US",	"José María"),
		("LOC_CITIZEN_LEU_MEXICO_MALE_2",			"en_US",	"Don Joaquín"),
		("LOC_CITIZEN_LEU_MEXICO_MALE_3",			"en_US",	"Eugenio"),
		("LOC_CITIZEN_LEU_MEXICO_MALE_4",			"en_US",	"Francisco Javier"),
		("LOC_CITIZEN_LEU_MEXICO_MALE_5",			"en_US",	"Fenando"),
		("LOC_CITIZEN_LEU_MEXICO_MALE_6",			"en_US",	"Jesús Ángel"),
		("LOC_CITIZEN_LEU_MEXICO_MALE_7",			"en_US",	"Pedro"),
		("LOC_CITIZEN_LEU_MEXICO_MALE_8",			"en_US",	"Roberto Gómez"),
		("LOC_CITIZEN_LEU_MEXICO_MALE_9",			"en_US",	"Federico"),
		("LOC_CITIZEN_LEU_MEXICO_MALE_10",			"en_US",	"Carlos"),
		-------------------------------------------------------- MODERNn Male ------------
		("LOC_CITIZEN_LEU_MEXICO_MODERN_MALE_1",		"en_US",	"Jorge"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_MALE_2",		"en_US",	"Eduardo"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_MALE_3",		"en_US",	"Roberto"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_MALE_4",		"en_US",	"Fernando"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_MALE_5",		"en_US",	"Francisco"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_MALE_6",		"en_US",	"Mario"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_MALE_7",		"en_US",	"Carlos"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_MALE_8",		"en_US",	"David"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_MALE_9",		"en_US",	"Guadalupe"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_MALE_10",	"en_US",	"Manuel"),
		------------------------------------------------------- Ancient Female ------------
		("LOC_CITIZEN_LEU_MEXICO_FEMALE_1",			"en_US",	"María Guadalupe"),
		("LOC_CITIZEN_LEU_MEXICO_FEMALE_2",			"en_US",	"María de Jesús"),
		("LOC_CITIZEN_LEU_MEXICO_FEMALE_3",			"en_US",	"María Isabel"),
		("LOC_CITIZEN_LEU_MEXICO_FEMALE_4",			"en_US",	"María Luisa"),
		("LOC_CITIZEN_LEU_MEXICO_FEMALE_5",			"en_US",	"María del Rosario"),
		("LOC_CITIZEN_LEU_MEXICO_FEMALE_6",			"en_US",	"María Elena"),
		("LOC_CITIZEN_LEU_MEXICO_FEMALE_7",			"en_US",	"María del Carmen"),
		("LOC_CITIZEN_LEU_MEXICO_FEMALE_8",			"en_US",	"María de los Ángeles"),
		("LOC_CITIZEN_LEU_MEXICO_FEMALE_9",			"en_US",	"Lupita"),
		("LOC_CITIZEN_LEU_MEXICO_FEMALE_10",		"en_US",	"Margarita"),
		------------------------------------------------------- MODERNn Female ------------
		("LOC_CITIZEN_LEU_MEXICO_MODERN_FEMALE_1",	"en_US",	"Juana"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_FEMALE_2",	"en_US",	"Francisca"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_FEMALE_3",	"en_US",	"Silvia"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_FEMALE_4",	"en_US",	"Gloria"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_FEMALE_5",	"en_US",	"Viviana"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_FEMALE_6",	"en_US",	"Teresa"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_FEMALE_7",	"en_US",	"Rubí"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_FEMALE_8",	"en_US",	"Ana María"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_FEMALE_9",	"en_US",	"Rosa María"),
		("LOC_CITIZEN_LEU_MEXICO_MODERN_FEMALE_10",	"en_US",	"Gabriela"),
---------------------------------------------------------------------------------------------------------------------------
-- City Names
----------------------------------------------------------------------------------------------------------------------------
		("LOC_CITY_NAME_LEU_MEXICO_CITY",				"en_US",		"Mexico City"),	
		("LOC_CITY_NAME_GUADALAJARA",					"en_US",		"Guadalajara"),	
		("LOC_CITY_NAME_VERACRUZ",						"en_US",		"Veracruz"),	
		("LOC_CITY_NAME_MONTERREY",						"en_US",		"Monterrey"),	
		("LOC_CITY_NAME_LEON",							"en_US",		"León"),	
		("LOC_CITY_NAME_SAN_LUIS_POTOSI",				"en_US",		"San Luis Potosí"),	
		("LOC_CITY_NAME_PUEBLA",						"en_US",		"Puebla"),	
		("LOC_CITY_NAME_ACAPULCO",						"en_US",		"Acapulco"),	
		("LOC_CITY_NAME_OAXACA",						"en_US",		"Oaxaca"),	
		("LOC_CITY_NAME_MERIDA",						"en_US",		"Mérida"),	
		("LOC_CITY_NAME_HERMOSILLO",					"en_US",		"Hermosillo"),	
		("LOC_CITY_NAME_TAMPICO",						"en_US",		"Tampico"),	
		("LOC_CITY_NAME_SAN_CRISTOBAL_DE_LAS_CASAS",	"en_US",		"San Cristóbal de las Casas"),	
		("LOC_CITY_NAME_MAZATLAN",						"en_US",		"Mazatlán"),	
		("LOC_CITY_NAME_MORELIA",						"en_US",		"Morelia"),	
		("LOC_CITY_NAME_VILLAHERMOSA",					"en_US",		"Villahermosa"),	
		("LOC_CITY_NAME_CUERNAVACA",					"en_US",		"Cuernavaca"),	
		("LOC_CITY_NAME_TORREON",						"en_US",		"Torreón"),	
		("LOC_CITY_NAME_SAN_FRANCISCO_DE_CAMPECHE",		"en_US",		"San Francisco de Campeche"),	
		("LOC_CITY_NAME_NUEVO_LAREDO",					"en_US",		"Nuevo Laredo"),	
		("LOC_CITY_NAME_CHIHUAHUA",						"en_US",		"Chihuahua"),	
		("LOC_CITY_NAME_CIUDAD_JUAREZ",					"en_US",		"Ciudad Juárez"),	
		("LOC_CITY_NAME_AGUASCALIENTES",				"en_US",		"Aguascalientes"),	
		("LOC_CITY_NAME_CANCUN",						"en_US",		"Cancún"),	
		("LOC_CITY_NAME_DURANGO",						"en_US",		"Durango"),	
		("LOC_CITY_NAME_TIJUANA",						"en_US",		"Tijuana"),	
		("LOC_CITY_NAME_REYNOSA",						"en_US",		"Reynosa"),	
		("LOC_CITY_NAME_TOLUCA",						"en_US",		"Toluca"),	
		("LOC_CITY_NAME_MATAMOROS",						"en_US",		"Matamoros"),	
		("LOC_CITY_NAME_SALTILLO",						"en_US",		"Saltillo"),	
		("LOC_CITY_NAME_ENSENADA",						"en_US",		"Ensenada"),	
		("LOC_CITY_NAME_NOGALES",						"en_US",		"Nogales"),	
		("LOC_CITY_NAME_COATZACOALCOS",					"en_US",		"Coatzacoalcos"),	
		("LOC_CITY_NAME_PUERTO_VALLARTA",				"en_US",		"Puerto Vallarta"),	
		("LOC_CITY_NAME_PIEDRAS_NEGRAS",				"en_US",		"Piedras Negras"),	
		("LOC_CITY_NAME_GUANAJUATO",					"en_US",		"Guanajuato"),	
		("LOC_CITY_NAME_MANZANILLO",					"en_US",		"Manzanillo"),	
		("LOC_CITY_NAME_ZACATECAS",						"en_US",		"Zacatecas"),	
		("LOC_CITY_NAME_IGUALA",						"en_US",		"Iguala"),	
		("LOC_CITY_NAME_PACHUCA",						"en_US",		"Pachuca"),	
		("LOC_CITY_NAME_QUERETARO",						"en_US",		"Querétaro"),	
		("LOC_CITY_NAME_COLIMA",						"en_US",		"Colima"),	
		("LOC_CITY_NAME_ORIZABA",						"en_US",		"Orizaba"),	
---------------------------------------------------------------------------------------------------------------------------
-- Geography Names
----------------------------------------------------------------------------------------------------------------------------
		("LOC_NAMED_RIVER_LEU_RIO_NAZAS_NAME",							"en_US",		"Río Nazas"),
		("LOC_NAMED_RIVER_LEU_RIO_GRANDE_DE_SANTIAGO_NAME",				"en_US",		"Río Grande de Santiago"),
		("LOC_NAMED_RIVER_LEU_RIO_CONCHOS_NAME",						"en_US",		"Río Conchos"),
		("LOC_NAMED_RIVER_LEU_RIO_GRIJALVA_NAME",						"en_US",		"Río Grijalva"),
		("LOC_NAMED_RIVER_LEU_RIO_LERMA_NAME",							"en_US",		"Río Lerma"),
		("LOC_NAMED_RIVER_LEU_RIO_BALSAS_NAME",							"en_US",		"Río Balsas"),
		("LOC_NAMED_RIVER_LEU_RIO_CULIACAN_NAME",						"en_US",		"Río Culiacán"),
		("LOC_NAMED_RIVER_LEU_RIO_USUMACINTA_NAME",						"en_US",		"Río Usumacinta"),
		("LOC_NAMED_RIVER_LEU_RIO_COLORADO_NAME",						"en_US",		"Río Colorado"),
		("LOC_NAMED_RIVER_LEU_RIO_BRAVO_NAME",							"en_US",		"Río Bravo"),
		("LOC_NAMED_MOUNTAIN_LEU_SIERRA_DE_LA_VIGA_NAME",				"en_US",		"Sierra de la Viga"),
		("LOC_NAMED_MOUNTAIN_LEU_CERRO_EL_POTOSI_NAME",					"en_US",		"Cerro el Potosí"),
		("LOC_NAMED_MOUNTAIN_LEU_SIERRA_DE_LA_MARTA_NAME",				"en_US",		"Sierra de la Marta"),
		("LOC_NAMED_MOUNTAIN_LEU_EL_COAHUILON_NAME",					"en_US",		"El Coahuilón"),
		("LOC_NAMED_MOUNTAIN_LEU_SIERRA_PENA_NEVADA_NAME",				"en_US",		"Sierra Peña Nevada"),
		("LOC_NAMED_MOUNTAIN_LEU_CERRO_EL_VEIJO_NAME",					"en_US",		"Cerro El Veijo"),
		("LOC_NAMED_MOUNTAIN_LEU_SIERRA_MORONES_NAME",					"en_US",		"Sierra Morones"),
		("LOC_NAMED_VOLCANO_LEU_LOS_ATLIXCOS_NAME",						"en_US",		"Los Atlixcos"),
		("LOC_NAMED_VOLCANO_LEU_VOLCAN_BARCENA_NAME",					"en_US",		"Volcán Bárcena"),
		("LOC_NAMED_VOLCANO_LEU_CEBORUCO_NAME",							"en_US",		"Ceboruco"),
		("LOC_NAMED_VOLCANO_LEU_CERRO_PRIETO_NAME",						"en_US",		"Cerro Prieto"),
		("LOC_NAMED_VOLCANO_LEU_EL_CHICHON_NAME",						"en_US",		"El Chichón"),
		("LOC_NAMED_VOLCANO_LEU_COFRE_DE_PEROTE_NAME",					"en_US",		"Cofre de Perote"),
		("LOC_NAMED_VOLCANO_LEU_COLIMA_NAME",							"en_US",		"Colima"),
		("LOC_NAMED_VOLCANO_LEU_COMONDU_NAME",							"en_US",		"Comondú"),
		("LOC_NAMED_VOLCANO_LEU_CORONADO_NAME",							"en_US",		"Coronado"),
		("LOC_NAMED_VOLCANO_LEU_LAS_CUMBRES_NAME",						"en_US",		"Las Cumbres"),
		("LOC_NAMED_VOLCANO_LEU_LAS_DERRUMBADAS_NAME",					"en_US",		"Las Derrumbadas"),
		("LOC_NAMED_VOLCANO_LEU_GUADALUPE_NAME",						"en_US",		"Guadalupe"),
		("LOC_NAMED_VOLCANO_LEU_LOS_HUMEROS_NAME",						"en_US",		"Los Humeros"),
		("LOC_NAMED_VOLCANO_LEU_IZTACCIHUATL_NAME",						"en_US",		"Iztaccihuatl"),
		("LOC_NAMED_VOLCANO_LEU_JOCOTITLAN_NAME",						"en_US",		"Jocotitlán"),
		("LOC_NAMED_VOLCANO_LEU_EL_JORULLO_NAME",						"en_US",		"El Jorullo"),
		("LOC_NAMED_VOLCANO_LEU_LA_MALINCHE_NAME",						"en_US",		"La Malinche"),
		("LOC_NAMED_VOLCANO_LEU_NEVADO_DE_TOLUCA_NAME",					"en_US",		"Nevado de Toluca"),
		("LOC_NAMED_VOLCANO_LEU_PAPAYO_NAME",							"en_US",		"Papayo"),
		("LOC_NAMED_VOLCANO_LEU_PARICUTIN_NAME",						"en_US",		"Parícutin"),
		("LOC_NAMED_VOLCANO_LEU_LA_REFORMA_CALDERA_NAME",				"en_US",		"La Reforma Caldera"),
		("LOC_NAMED_VOLCANO_LEU_SOCORRO_NAME",							"en_US",		"Socorro"),
		("LOC_NAMED_VOLCANO_LEU_TEQUILA_NAME",							"en_US",		"Tequila Volcano"),
		("LOC_NAMED_DESERT_LEU_DESIERTO_DE_SONORA_NAME",				"en_US",		"Desierto de Sonora"),
		("LOC_NAMED_DESERT_LEU_DESIERTO_DE_CHIHUAHUA_NAME",				"en_US",		"Desierto de Chihuahua"),
		("LOC_NAMED_DESERT_LEU_DESIERTO_DEL_COLORADO_NAME",				"en_US",		"Desierto del Colorado"),
		("LOC_NAMED_DESERT_LEU_EL_VIZCAINO_NAME",						"en_US",		"El Vizcaíno"),
		("LOC_NAMED_DESERT_LEU_DESIERTO_DE_BAJA_CALIFORNIA_NAME",		"en_US",		"Desierto de Baja California"),
		("LOC_NAMED_DESERT_LEU_GRAN_DESIERTO_DE_ALTAR_NAME",			"en_US",		"Gran Desierto de Altar"),
		("LOC_NAMED_DESERT_LEU_MEDANOS_DE_SAMALAYUCA_NAME",				"en_US",		"Médanos de Samalayuca"),
		("LOC_NAMED_DESERT_LEU_DESIERTO_DE_YUMA_NAME",					"en_US",		"Desierto de Yuma"),
		("LOC_NAMED_LAKE_LEU_LAGO_DE_CHAPALA_NAME",						"en_US",		"Lago de Chapala"),
		("LOC_NAMED_LAKE_LEU_LAGUNA_DE_BACALAR_NAME",					"en_US",		"Laguna de Bacalar"),
		("LOC_NAMED_LAKE_LEU_LAGO_DE_CHAPULTEPEC_NAME",					"en_US",		"Lago de Chapultepec"),
		("LOC_NAMED_LAKE_LEU_LAGO_CAMECUARO_NAME",						"en_US",		"Lago Camecuaro"),
		("LOC_NAMED_LAKE_LEU_LAGOS_DE_MONTEBELLO_NAME",					"en_US",		"Lagos de Montebello"),
		("LOC_NAMED_LAKE_LEU_LAGUNA_NICHUPTE_NAME",						"en_US",		"Laguna Nichupté"),
		("LOC_NAMED_LAKE_LEU_LAGO_AVANDARO_NAME",						"en_US",		"Lago Avándaro"),
		("LOC_NAMED_LAKE_LEU_BARRA_DE_COYUCA_NAME",						"en_US",		"Barra de Coyuca"),
		("LOC_NAMED_LAKE_LEU_LAGUNO_DE_TERMINOS_NAME",					"en_US",		"Laguna de Términos"),
		("LOC_NAMED_LAKE_LEU_LAGUNA_DE_CATEMACO_NAME",					"en_US",		"Laguna de Catemaco"),
		("LOC_NAMED_LAKE_LEU_LAGUNA_POJOJ_NAME",						"en_US",		"Laguna Pojoj"),
		("LOC_NAMED_LAKE_LEU_LAGO_ARAREKO_NAME",						"en_US",		"Lago Arareko"),
		("LOC_NAMED_LAKE_LEU_LAGO_DE_PATZCUARO_NAME",					"en_US",		"Lago de Pátzcuaro"),
		("LOC_NAMED_LAKE_LEU_LAGUNA_OJO_DE_LIEBRE_NAME",				"en_US",		"Laguna Ojo de Liebre"),
		("LOC_NAMED_SEA_LEU_BAHIA_DE_BANDERAS_NAME",					"en_US",		"Bahía de Banderas"),
		("LOC_NAMED_SEA_LEU_BAHIA_ADAIR_NAME",							"en_US",		"Bahía Adair"),
		("LOC_NAMED_SEA_LEU_BAHIA_DE_GUAYMAS_NAME",						"en_US",		"Bahía de Guaymas"),
		("LOC_NAMED_SEA_LEU_BAHIA_DE_LA_PAZ_NAME",						"en_US",		"Bahía de la Paz"),
		("LOC_NAMED_SEA_LEU_BAHIA_DE_TEPOCA_NAME",						"en_US",		"Bahía de Tepoca"),
		("LOC_NAMED_SEA_LEU_GOLFO_DE_CALIFORNIA_NAME",					"en_US",		"Golfo de California"),
		("LOC_NAMED_SEA_LEU_ENSENADA_DE_PABELLONES_NAME",				"en_US",		"Ensenada de Pabellones"),
		("LOC_NAMED_SEA_LEU_BAHIA_DE_MAGDALENA_NAME",					"en_US",		"Bahía de Magdalena"),
		("LOC_NAMED_SEA_LEU_BAHIA_DE_SAN_QUINTIN_NAME",					"en_US",		"Bahía de San Quintín"),
		("LOC_NAMED_SEA_LEU_BAHIA_DE_SEBASTIAN_VIZCAINO_NAME",			"en_US",		"Bahía de Sebastián Vizcaíno"),
		("LOC_NAMED_SEA_LEU_GOLFO_DE_TEHUANTEPEC_NAME",					"en_US",		"Golfo de Tehuantepec"),
		("LOC_NAMED_SEA_LEU_OCEANO_PACIFICO_NAME",						"en_US",		"Oceano Pacífico"),
		("LOC_NAMED_SEA_LEU_OCEANO_ATLANTICO_NAME",						"en_US",		"Oceano Atlántico");
--==========================================================================================================================
--==========================================================================================================================
