-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType)
VALUES 	('LEADER_SC_LENIN_TECHS'),
		('LEADER_SC_LENIN_CIVICS'),
		('LEADER_SC_LENIN_DISTRICTS'),
		('LEADER_SC_LENIN_BUILDINGS'),
		('LEADER_SC_LENIN_PROJECTS'),
		('LEADER_SC_LENIN_DIPLOMACY'),
		('LEADER_SC_LENIN_EXPANSION'),
		('LEADER_SC_LENIN_PSUEDOS');

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,							LeaderType,							System)
VALUES  ('LEADER_SC_LENIN_TECHS',			'TRAIT_LEADER_SC_RED_OCTOBER',		'Technologies'),
		('LEADER_SC_LENIN_CIVICS',			'TRAIT_LEADER_SC_RED_OCTOBER',		'Civics'),
		('LEADER_SC_LENIN_DISTRICTS',		'TRAIT_LEADER_SC_RED_OCTOBER',		'Districts'),
		('LEADER_SC_LENIN_BUILDINGS',		'TRAIT_LEADER_SC_RED_OCTOBER',		'Buildings'),
		('LEADER_SC_LENIN_PROJECTS',		'TRAIT_LEADER_SC_RED_OCTOBER',		'Projects'),
		('LEADER_SC_LENIN_DIPLOMACY',		'TRAIT_LEADER_SC_RED_OCTOBER',		'DiplomaticActions'),
		('LEADER_SC_LENIN_EXPANSION',		'TRAIT_LEADER_SC_RED_OCTOBER',		'PlotEvaluations'),
		('LEADER_SC_LENIN_PSUEDOS',			'TRAIT_LEADER_SC_RED_OCTOBER',		'PsuedoYields');
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,							Item,										Favored)
VALUES  -- TECHS
		('LEADER_SC_LENIN_TECHS',			'TECH_MINING',								1),
		('LEADER_SC_LENIN_TECHS',			'TECH_WRITING',								1),
		('LEADER_SC_LENIN_TECHS',			'TECH_BRONZE_WORKING',						1),
		('LEADER_SC_LENIN_TECHS',			'TECH_APPRENTICESHIP',						1),
		('LEADER_SC_LENIN_TECHS',			'TECH_GUNPOWDER',							1),
		('LEADER_SC_LENIN_TECHS',			'TECH_SIEGE_TACTICS',						1),
		('LEADER_SC_LENIN_TECHS',			'TECH_INDUSTRIALIZATION',					1),
		('LEADER_SC_LENIN_TECHS',			'TECH_MILITARY_SCIENCE',					1),
		('LEADER_SC_LENIN_TECHS',			'TECH_ECONOMICS',							1),
		('LEADER_SC_LENIN_TECHS',			'TECH_REPLACEABLE_PARTS',					1),
		('LEADER_SC_LENIN_TECHS',			'TECH_RADIO',								1),
		-- CIVICS
		('LEADER_SC_LENIN_CIVICS',			'CIVIC_MILITARY_TRADITION',					1),
		('LEADER_SC_LENIN_CIVICS',			'CIVIC_STATE_WORKFORCE',					1),
		('LEADER_SC_LENIN_CIVICS',			'CIVIC_DEFENSIVE_TACTICS',					1),
		('LEADER_SC_LENIN_CIVICS',			'CIVIC_URBANIZATION',						1),
		('LEADER_SC_LENIN_CIVICS',			'CIVIC_SCORCHED_EARTH',						1),
		('LEADER_SC_LENIN_CIVICS',			'CIVIC_IDEOLOGY',							1),
		('LEADER_SC_LENIN_CIVICS',			'CIVIC_CLASS_STRUGGLE',						1),
		('LEADER_SC_LENIN_CIVICS',			'CIVIC_COLD_WAR',							1),
		('LEADER_SC_LENIN_CIVICS',			'CIVIC_SPACE_RACE',							1),
		-- DISTRICTS
		('LEADER_SC_LENIN_DISTRICTS',		'DISTRICT_INDUSTRIAL_ZONE',					1),
		('LEADER_SC_LENIN_DISTRICTS',		'DISTRICT_CAMPUS',							1),
		('LEADER_SC_LENIN_DISTRICTS',		'DISTRICT_ENCAMPMENT',						1),
		-- BUILDINGS
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_WORKSHOP',						1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_FACTORY',							1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_POWER_PLANT',						1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_LIBRARY',							1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_UNIVERSITY',						1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_RESEARCH_LAB',					1),
		-- WONDERS
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_BROADWAY',						1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_ESTADIO_DO_MARACANA',				1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_FORBIDDEN_CITY',					1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_GREAT_LIBRARY',					1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_HALICARNASSUS_MAUSOLEUM',			1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_OXFORD_UNIVERSITY',				1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_RUHR_VALLEY',						1),
		('LEADER_SC_LENIN_BUILDINGS',		'BUILDING_VENETIAN_ARSENAL',				1),
		-- PROJECTS
		('LEADER_SC_LENIN_PROJECTS',		'PROJECT_ENHANCE_DISTRICT_ENCAMPMENT',		1),
		('LEADER_SC_LENIN_PROJECTS',		'PROJECT_ENHANCE_DISTRICT_INDUSTRIAL_ZONE',	1),
		('LEADER_SC_LENIN_PROJECTS',		'PROJECT_ENHANCE_DISTRICT_CAMPUS',			1),
		-- DIPLOMACY
		('LEADER_SC_LENIN_DIPLOMACY',		'DIPLOACTION_DECLARE_FORMAL_WAR',			1),
		('LEADER_SC_LENIN_DIPLOMACY',		'DIPLOACTION_DECLARE_WAR_MINOR_CIV',		1);
		
INSERT INTO AiFavoredItems
		(ListType,							Item,										Favored,	Value,	StringVal)
VALUES  -- EXPANSION
		('LEADER_SC_LENIN_EXPANSION',		'Resource Class',							1,			5,		'RESOURCECLASS_STRATEGIC'),
		-- PSUEDOS
		('LEADER_SC_LENIN_PSUEDOS',			'PSEUDOYIELD_GPP_ENGINEER',					1,			25,		null),
		('LEADER_SC_LENIN_PSUEDOS',			'PSEUDOYIELD_GPP_SCIENTIST',				1,			25,		null),
		('LEADER_SC_LENIN_PSUEDOS',			'PSEUDOYIELD_GPP_GENERAL',					1,			25,		null);
