--- YNAEMP
CREATE TABLE IF NOT EXISTS StartPosition (MapName TEXT, Civilization TEXT, Leader TEXT, X INT default 0, Y INT default 0);
INSERT INTO StartPosition
		(Civilization,			Leader,					MapName,			X,	Y)
VALUES	('CIVILIZATION_JFD_ITALY',	'LEADER_SC_MATILDE',	'GiantEarth',			19,	61),
		('CIVILIZATION_JFD_ITALY',	'LEADER_SC_MATILDE',	'GreatestEarthMap',		50, 46),
		('CIVILIZATION_JFD_ITALY',	'LEADER_SC_MATILDE',	'LargestEarth',			24, 77),
		('CIVILIZATION_JFD_ITALY',	'LEADER_SC_MATILDE',	'PlayEuropeAgain',		42, 41),
		('CIVILIZATION_JFD_ITALY',	'LEADER_SC_MATILDE',	'LargeEurope',			34, 36),
		('CIVILIZATION_JFD_ITALY',	'LEADER_SC_MATILDE',	'CordiformEarth',		36, 25);

CREATE TABLE IF NOT EXISTS 
	Leader_Titles (
	LeaderType	TEXT 			 		DEFAULT NULL,
	GovernmentType			TEXT		DEFAULT NULL,
	LeaderTitle				TEXT		DEFAULT NULL,
	PolicyType  			TEXT 		DEFAULT NULL,
	UseFeminine				BOOLEAN		DEFAULT 0,
	TitleIsFullName			BOOLEAN		DEFAULT 0
	);
	
INSERT INTO Leader_Titles
		(LeaderType, 				GovernmentType, 							PolicyType,				LeaderTitle)
VALUES	('LEADER_SC_MATILDE',		'GOVERNMENT_CHIEFDOM',						null,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_SC_MATILDE'),					--Chiefdom
		('LEADER_SC_MATILDE',		'GOVERNMENT_JFD_HORDE',						null,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_SC_MATILDE'),					--Horde
		('LEADER_SC_MATILDE',		'GOVERNMENT_JFD_POLIS',						null,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_SC_MATILDE'),					--Polis
		('LEADER_SC_MATILDE',		'GOVERNMENT_AUTOCRACY',						null,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_SC_MATILDE'),				--Autocracy
		('LEADER_SC_MATILDE',		'GOVERNMENT_OLIGARCHY',						null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_SC_MATILDE'),				--Oligarchy
		('LEADER_SC_MATILDE',		'GOVERNMENT_CLASSICAL_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_SC_MATILDE'),		--Classical Democracy
		('LEADER_SC_MATILDE',		'GOVERNMENT_MERCHANT_REPUBLIC',				null,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_SC_MATILDE'),		--Merchant Republic
		('LEADER_SC_MATILDE',		'GOVERNMENT_THEOCRACY',						null,					'LOC_GOVERNMENT_JFD_THEOCRACY_LEADER_TITLE_SC_MATILDE'),		--Theocracy
		('LEADER_SC_MATILDE',		'GOVERNMENT_MONARCHY',						null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_SC_MATILDE'),					--Feudal Monarchy
		('LEADER_SC_MATILDE',		'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			null,					'LOC_GOVERNMENT_JFD_ABSOLUTE_MONARCHY_LEADER_TITLE_SC_MATILDE'),					--Absolute Monarchy
		('LEADER_SC_MATILDE',		'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	null,					'LOC_GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY_LEADER_TITLE_SC_MATILDE'),					--Constitutional Monarchy
		('LEADER_SC_MATILDE',		'GOVERNMENT_JFD_NOBLE_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_SC_MATILDE'),			--Noble Republic
		('LEADER_SC_MATILDE',		'GOVERNMENT_DEMOCRACY',						null,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_SC_MATILDE'),		--People's Republic
		('LEADER_SC_MATILDE',		'GOVERNMENT_COMMUNISM',						null,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_SC_MATILDE'),			--People's Republic
		('LEADER_SC_MATILDE',		'GOVERNMENT_FASCISM',						null,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_SC_MATILDE'),	--Military Guardianship
		('LEADER_SC_MATILDE',		null,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_SC_MATILDE');					--Empire

DELETE FROM Leader_Titles 
WHERE LeaderType = 'LEADER_SC_MATILDE' AND GovernmentType IS NOT null
AND GovernmentType NOT IN (SELECT GovernmentType FROM Governments);

DELETE FROM Leader_Titles 
WHERE LeaderType = 'LEADER_SC_MATILDE' AND PolicyType IS NOT null
AND PolicyType NOT IN (SELECT PolicyType FROM Policies);

-----------------------------------------------
-- 40sw4rm's "Old World"
-----------------------------------------------
CREATE TABLE IF NOT EXISTS TSL 
    (
    MapType TEXT DEFAULT NULL,
    Civ TEXT DEFAULT NULL,
    LeaderType TEXT DEFAULT NULL,
    X INTEGER DEFAULT NULL,
    Y INTEGER DEFAULT NULL
    );

INSERT INTO TSL(MapType,Civ,LeaderType,X,Y)
VALUES
('40sw4rmOW',	'CIVILIZATION_JFD_ITALY',		'LEADER_SC_MATILDE',		20, 51);